package de.hdm_stuttgart.se2_projekt.pascalWiss.data;

/**
 * Exception for a String when it is Null
 *
 */
public class StringNullException extends Exception {

	/**
	 * Autogenerated Id
	 */
	private static final long serialVersionUID = -1451797759806825214L;

	public StringNullException() {
		super("String is NULL!");
	}

}
